on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: npaka06/github-test-action@v4
      with:
        who-to-greet: 'Mona the Octocat'
    - run: echo Hello from pipeline test 
      shell: bash
